### ISSUE TITLE
Run ConQuR without covariates

### ISSUE THREAD

**Issue by andrewmaltezthomas** [wdl2459/ConQuR#3]
Hi ConQuR developers, 

I was wondering if there was a way to run the ConQuR() command without including any covariates, so just the batch. I tried using NULL, which returned an error:

`Error in data.frame(covariates, batchid) : 
  arguments imply differing number of rows: 0, 147`

And I also tried using a vector with the batchIDs, which returned an identical count matrix to the original. 

Thanks in advance.

**Comment by tommyfuu** [comment]
ran into the same issue, agree that this is probably a feature that needs to be added.

one thing i notice though is that the resultant dataframe from ConQuR is not that different from the original dataframe in general. I tried running ConQuR on a dataframe with covariates, as well as a dataframe without covariates where I used batchIDs as the placeholder covariate. looked pretty carefully and did notice subtle differences between the resultant dataframe and the input.

That might be worth double-checking?

**Comment by wdl2459** [comment]
Thank you for the question! To use ConQuR without covariates, please make simple_match=T and keep covariates=NULL. Please let me know whether it works.

**Comment by tommyfuu** [comment]
that worked like a charm for me! thank you so much!

**Comment by andrewmaltezthomas** [comment]
Also worked for me. Thanks!
