### ISSUE TITLE
code for simulation experiments

### ISSUE THREAD

**Issue by tommyfuu** [wdl2459/ConQuR#4]
hi ConQuR developers,

hope you are well! I am wondering if you could provide the code for the simulation experiments as described in the paper and its supplemental materials? That will be really appreciated. Thanks!

**Comment by wdl2459** [comment]
Sure. May I know the best way to share the codes with you?

**Comment by tommyfuu** [comment]
hi!

Email would work - if you have it up on any online repository you could also email me the link! I also noticed that you are a professor at Weill Cornell! My WCM email is `chf4012@med.cornell.edu`.

Thank you so much!
